// scheduler.ts
//
// Polls every device's devices/<device>/tasks/ every SCHEDULER_POLL_INTERVAL_MS
// and fires anything due, independently per device — one device's
// stuck/erroring task never blocks another device's. Started from index.ts
// once devices are booted (needs each device's own client for chat-name
// resolution and delivery — see resolveChatIdByName/fireTask below).

import { CronExpressionParser } from "cron-parser";
import { callAgent, callNamedAgent } from "./agent.ts";
import { sendAgentResponse } from "./lib/send-agent-response.ts";
import { listActiveTaskNames, readTask, updateLastRun, archiveTask, readTaskMemory, type ScheduledTask } from "./lib/tasks.ts";

const POLL_INTERVAL_MS = process.env.SCHEDULER_POLL_INTERVAL_MS
    ? Number(process.env.SCHEDULER_POLL_INTERVAL_MS)
    : 60000;

// Guards against a slow agent call overlapping the next tick, per device —
// a Set instead of a single boolean since devices poll independently.
const pollingDevices = new Set<string>();

export interface DeviceHandle {
    name: string;
    client: any;
}

// `devices` is read fresh on every tick (via .forEach on whatever array is
// passed in) — index.ts mutates this same array in place as new devices
// come online via the onboarding poller, so newly added devices are picked
// up automatically without restarting this interval.
export function startScheduler(devices: DeviceHandle[]): void {
    console.log(`[scheduler] started, polling every ${POLL_INTERVAL_MS}ms`);
    setInterval(() => {
        devices.forEach((d) => void pollOnce(d.name, d.client));
    }, POLL_INTERVAL_MS);
}

async function pollOnce(deviceName: string, client: any): Promise<void> {
    if (pollingDevices.has(deviceName)) return;
    pollingDevices.add(deviceName);
    try {
        for (const name of listActiveTaskNames(deviceName)) {
            const task = readTask(deviceName, name);
            if (!task || task.status !== "active") continue;
            try {
                if (isDue(task)) {
                    console.log(`[scheduler] [${deviceName}] firing task '${task.name}'`);
                    await fireTask(deviceName, client, task);
                }
            } catch (err) {
                // Left last-run/location untouched on purpose — retried
                // next poll, no dead-letter mechanism.
                console.error(`[scheduler] [${deviceName}] task '${task.name}' failed:`, err);
            }
        }
    } finally {
        pollingDevices.delete(deviceName);
    }
}

export function isDue(task: ScheduledTask): boolean {
    const now = new Date();
    if (task.scheduleType === "once") {
        return now >= new Date(task.schedule);
    }
    const prev = CronExpressionParser.parse(task.schedule, { tz: task.timezone, currentDate: now }).prev().toDate();
    if (!task.lastRun) return prev <= now;
    return prev > new Date(task.lastRun);
}

// Wraps a recurring task's body with its prior continuity notes (if any)
// and a write-back instruction, so the agent has explicit, curated context
// instead of relying on conversation history that no longer persists across
// firings (see fireTask's threadId below). One-off tasks never call this —
// they have no continuity concept at all.
export function buildRecurringPrompt(task: ScheduledTask, priorNotes: string | undefined): string {
    // Relative to the device's own directory, not the app root — my_write_file
    // (see lib/device-scoped-path.ts) auto-prefixes with devices/<device>/,
    // so the agent-facing path here must NOT include that prefix itself.
    const memoryPath = `tasks/memory/${task.name}.md`;
    if (priorNotes) {
        return (
            `## Notes from previous runs\n\n${priorNotes}\n\n---\n\n## This run's task\n\n${task.body}\n\n` +
            `If anything from this run is worth remembering next time, update your notes using the ` +
            `write_file tool at ${memoryPath} — keep it concise (distilled notes, not a raw transcript); ` +
            `overwrite rather than append.`
        );
    }
    return (
        `${task.body}\n\nThis is the first run of this recurring task. If continuity across future runs would ` +
        `help (e.g. tracking progress, avoiding repeats), create ${memoryPath} with concise notes using the ` +
        `write_file tool, and keep it updated on future runs.`
    );
}

// Tolerant of a missing/extra leading "@" and case differences — a
// destination-chat value typed or generated by an LLM (see
// tools/create-scheduled-task.tool.ts) commonly drops the "@" a display
// name like "@jlabrada71" starts with (it reads as an @-mention), and an
// exact-match comparison would otherwise silently fail delivery.
function normalizeChatName(name: string): string {
    return name.trim().replace(/^@/, "").toLowerCase();
}

async function resolveChatIdByName(client: any, name: string): Promise<string | undefined> {
    // Same window.require('WAWebCollections').Chat.getModelsArray()
    // approach bot.ts's "list channels" command uses, reversed: name -> id
    // instead of id -> name.
    const chats: { name: string; id: string }[] = await client.pupPage!.evaluate(() => {
        // @ts-ignore - window.require is whatsapp-web.js's own webpack
        // module loader, injected into the page, not typed. The global
        // window.Store shim was dropped as of whatsapp-web.js@1.34.7.
        return window.require('WAWebCollections').Chat.getModelsArray().map((chat: any) => ({
            name: chat.isGroup ? `${chat.formattedTitle || chat.name} (group)` : chat.formattedTitle || chat.name || chat.id.user,
            id: chat.id._serialized,
        }));
    });
    const target = normalizeChatName(name);
    return chats.find((c) => normalizeChatName(c.name) === target)?.id;
}

async function fireTask(deviceName: string, client: any, task: ScheduledTask): Promise<void> {
    const chatId = await resolveChatIdByName(client, task.destinationChat);
    if (!chatId) {
        throw new Error(`destination chat '${task.destinationChat}' not found`);
    }

    // A fresh, unique local thread id every single firing — never reused
    // across runs of the same task (agent.ts/named-agents.ts wrap this in
    // the device: prefix internally). This is the actual fix for the
    // exceed_context_size_error crash: a fixed id let raw tool-call history
    // accumulate forever across firings. Continuity a recurring task needs
    // comes from the explicit tasks/memory/ file instead.
    const localThreadId = `scheduled:${task.name}:${Date.now()}`;

    const body =
        task.scheduleType === "recurring" ? buildRecurringPrompt(task, readTaskMemory(deviceName, task.name)) : task.body;

    const response =
        task.targetAgent === "default"
            ? await callAgent(deviceName, body, localThreadId)
            : await callNamedAgent(deviceName, task.targetAgent, body, localThreadId);

    await sendAgentResponse(client, chatId, response);

    if (task.scheduleType === "once") {
        archiveTask(deviceName, task.name, "completed");
    } else {
        updateLastRun(deviceName, task.name, new Date().toISOString());
    }
}
